cloud_id: "LLM-Test:dXMtZWFzdC0xLmF3cy5mb3VuZC5pbzo0NDMkYjM2ZWY3Mjg5M2E3NDIwNjkyMTUzN2FkMDA2Zjc1YmEkNjk2ZGRiZmNkODM2NDIzNWFlMDRlNDE4MGI1ZWNmNGI="
username: "elastic"
password: "4tDKz8RjJGkTugyWlSLjzQXL"
index_name: "search-sysco-recipes"
OpenAPIKey: "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"