cloud_id: "LLM-Test:dXMtZWFzdC0xLmF3cy5mb3VuZC5pbzo0NDMkYjM2ZWY3Mjg5M2E3NDIwNjkyMTUzN2FkMDA2Zjc1YmEkNjk2ZGRiZmNkODM2NDIzNWFlMDRlNDE4MGI1ZWNmNGI="
username: "elastic"
password: "9faSLDyTDIXH4VdHO47MKmOz"
index_name: "search-sysco-recipes"
OpenAPIKey: "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"